baseURL = 'https://krishnakalesh.github.io/pinchofcode/'
languageCode = 'en-us'
title = 'Pinch of Code'
theme = "github-style"
googleAnalytics = ""
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Krishna Kalesh"
  description = "In solitude, where we are least alone."
  github = "krishnakalesh"
  facebook = "criskalesh"
  twitter = "criskalesh"
  linkedin = "krishnakalesh"
  email = "krishnakaleshb@gmail.com"
  keywords = "blog, google analytics"
  rss = true
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/pinchofcode/images/github.png"
  avatar = "/pinchofcode/images/avatar.png"
  headerIcon = "/pinchofcode/images/GitHub-Mark-Light-32px.png"
  location = "India"
  enableGitalk = true

  [params.gitalk]
    clientID = "1797648028c1f1a543f9"
    clientSecret = "39589f861950278dc7d6b2fb66ceccf346009a96"
    repo = "pinchofcode"
    owner = "krishnakalesh"
    admin = "krishnakalesh"
    id = "location.pathname"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = false
    distractionFreeMode = false

  [[params.links]]
    title = "Link"
    href = "https://github.com/krishnakalesh"
  [[params.links]]
    title = "Link2"
    href = "https://krishnakalesh.com"
    icon = "/pinchofcode/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]